Fix expected NIC version response for fbttn
Summary:
FWUtilVersion test is failing for brycecanyon with:
```
======================================================================
FAIL: test_version_header (tests.fbttn.test_fw_util.FwUtilVersionTest) [nic]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/run/tests2/tests/fbttn/test_fw_util.py", line 41, in test_version_header
    comps[comp_name]["version header"]
  File "/run/tests2/common/base_fw_util_test.py", line 43, in verify_output
    self.assertRegex(out, regex, msg=msg)
AssertionError: Regex didn't match: '^.*NIC version.*$' not found in 'Broadcom NIC Version: 20.6.4.18\n' : fw-util version not match, expect '^.*NIC version.*$' but not found
```
However, this would never pass as the actual output seems to be consistently:
```
$ for host in $(randoob 10 brycecanyon1); do ssh -o LogLevel=ERROR root@$host "fw-util all --version | grep NIC"; done
Broadcom NIC Version: 20.6.4.18
Broadcom NIC Version: 20.6.4.18
Mellanox NIC Version: 14.27.2606
Mellanox NIC Version: 14.27.2606
Broadcom NIC Version: 20.6.4.18
Mellanox NIC Version: 14.27.2606
Broadcom NIC Version: 20.6.4.18
Mellanox NIC Version: 14.27.2606
Broadcom NIC Version: 20.6.4.18
Mellanox NIC Version: 14.27.2606
```

Test Plan:
```
$ python3 tests2/openbmc_tester.py --hostname twstorage14893-oob.ash8.facebook.com --port 22 --password ******** --platform fbttn
```
Confirm version_header passes:
```
test_version_header (tests.fbttn.test_fw_util.FwUtilVersionTest) ... ok
```

Reviewed By: doranand

Differential Revision: D68710050

fbshipit-source-id: 1513610e5f504032536f5e4bc3e3812c01cedfe2