ventura: add patch for PVT build image
Summary:
The current kernel DTS patch encounters a "could not apply" error.

```
(1/64) 0001-meta-facebook-ventura-Add-Linux-device-tree-related-led.patch | [INFO]: check of .kernel-meta//patches//./0001-meta-facebook-ventura-Add-Linux-device-tree-related-led.patch with "git am" did not pass, trying reduced context. | [INFO]: Context reduced git-am of .kernel-meta//patches//./0001-meta-facebook-ventura-Add-Linux-device-tree-related-led.patch with "git am" did not work, trying "apply". | /home/yangchen/project/ventura/openbmc.quanta/build/tmp/work-shared/ventura/kernel-source/.git/rebase-apply/patch:228: trailing whitespace. | 			gpios = <&tray_leds_g4_gpio 3 GPIO_ACTIVE_LOW>; | /home/yangchen/project/ventura/openbmc.quanta/build/tmp/work-shared/ventura/kernel-source/.git/rebase-apply/patch:595: trailing whitespace. | 		};
| fatal: .git/index: index file smaller than expected | [ERROR]: Application of .kernel-meta//patches//./0001-meta-facebook-ventura-Add-Linux-device-tree-related-led.patch failed.
|          Patch needs to be refreshed. Sample resolution script:
|              .git/rebase-apply/resolve_rejects
| ERROR: Could not apply patches for aspeed.
| ERROR: Patch failures can be resolved in the linux source directory /home/yangchen/project/ventura/openbmc.quanta/build/tmp/work-shared/ventura/kernel-source)
| WARNING: exit code 1 from a shell command.
ERROR: Task (/home/yangchen/project/ventura/openbmc.quanta/yocto/lf-master/meta-aspeed/recipes-kernel/linux/linux-aspeed_git.bb:do_patch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3140 tasks of which 3138 didn't need to be rerun and 1 failed.
```

Reverting to an earlier patch and adding a new patch for the PVT build DTS with the following changes:

1. Add gpio-led for each tray led control.
2. Remove the power monitor IC defined in DTS because multiple sources of the RMC board have the same i2c address.
3. Add 2nd HSC xdp710.

Additionally, add a patch for the Entity Manager with the configuration used by Ventura.
Lore Link: https://gerrit.openbmc.org/c/openbmc/entity-manager/+/78154

X-link: https://github.com/facebookexternal/openbmc.quanta/pull/4561

Reviewed By: williamspatrick

Differential Revision: D69467220

fbshipit-source-id: a19ec6a37eaf406fbc04c2fa999ca7adc0e7f8f5