log-util: fix test case build
Summary:
On some systems, log-util fails to compile under ptest with:
```
| /usr/src/debug/log-util/0.2/tests/test_logutil.cpp:10:7: error: type 'struct MockSELFormat' violates the C++ One Definition Rule [-Werror=odr]
| /usr/src/debug/log-util/0.2/tests/test_selformat.cpp:33:7: note: a different type is defined in another translation unit
| /usr/src/debug/log-util/0.2/tests/test_logutil.cpp:14:3: note: the first difference of corresponding definitions is field 'gmock01_get_fru_name_14'
| /usr/src/debug/log-util/0.2/tests/test_selformat.cpp:37:3: note: a field with different name is defined in another translation unit
| /usr/src/debug/log-util/0.2/tests/test_logutil.cpp:18:7: error: type 'struct MockSELStream' violates the C++ One Definition Rule [-Werror=odr]
| /usr/src/debug/log-util/0.2/tests/test_selstream.cpp:17:7: note: a different type is defined in another translation unit
| /usr/src/debug/log-util/0.2/tests/test_logutil.cpp:21:3: note: the first difference of corresponding definitions is field 'gmock01_make_sel_21'
| /usr/src/debug/log-util/0.2/tests/test_selstream.cpp:20:3: note: a field with different name is defined in another translation unit
```

There are multiple structures named `MockSELStream` and `MockSELFormat`
in different test cases, which were attempted to compile into a single
executable.  Adjust the `meson.build` so that there is a test executable
per test case.

Test Plan: Compiles successfully and ptest passes.

Reviewed By: amithash

Differential Revision: D71637565

fbshipit-source-id: 19c58ed68dace875e7a2184e7d7061742148f72a