icecube800bc: leakage-mond: add leakage-mond to support icecube800bc
Summary:
# Description
- icecube800bc: leakage-mond: add leakage-mond to support icecube800bc
- icecube800bc: openbmc-utils: add GPIO related leakage detector

# Motivation
To support Liquid Cooling leakage detector in icecube800bc platform

- detect GPIO LEAK_BMC_L
- when the signal is LOW
- BMC record the event and set GPIO LEAK_DISABLE_PWR_L to LOW till system cycle

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1859

Test Plan:
validated in Icecube EVT,
set MCBCPLD register to simulate leakage signal

```
root@bmc-oob:~# systemctl status leakage-mond
● leakage-mond.service - Run leakage-mond in OpenBMC
     Loaded: loaded (/usr/lib/systemd/system/leakage-mond.service; enabled; preset: enabled)
     Active: active (running) since Thu 2024-12-19 15:48:02 PST; 5s ago
 Invocation: 795098e4e5484746a214472bb672a74b
    Process: 822 ExecStartPre=/bin/sh -c /usr/bin/echo "both" > /tmp/gpionames/LEAK_BMC_L/edge (code=exited, status=0/SUCCESS)
   Main PID: 825 (leakage-mond)
        CPU: 67ms
     CGroup: /system.slice/leakage-mond.service
             └─825 /usr/local/bin/leakage-mond -e -i -o -I /tmp/gpionames/LEAK_BMC_L/value -O /tmp/gpionames/LEAK_DISABLE_PWR_L/value

Dec 19 15:48:02 bmc-oob. systemd[1]: Starting Run leakage-mond in OpenBMC...
Dec 19 15:48:02 bmc-oob. systemd[1]: Started Run leakage-mond in OpenBMC.
Dec 19 15:48:02 bmc-oob. leakage-mond[825]: Starting Leakage-monitor
Dec 19 15:48:02 bmc-oob. leakage-mond[825]: Initial leakage state: normal
Dec 19 15:48:02 bmc-oob. leakage-mond[825]: Polling for event
root@bmc-oob:~# i2cget -f -y 12 0x60 0x15
0xff
root@bmc-oob:~# cat /tmp/gpionames/LEAK_BMC_L/value
1
root@bmc-oob:~# cat /tmp/gpionames/LEAK_DISABLE_PWR_L/value
1
root@bmc-oob:~# i2cset -f -y 12 0x60 0x15 0xf7
root@bmc-oob:~# systemctl status leakage-mond
● leakage-mond.service - Run leakage-mond in OpenBMC
     Loaded: loaded (/usr/lib/systemd/system/leakage-mond.service; enabled; preset: enabled)
     Active: active (running) since Thu 2024-12-19 15:48:02 PST; 1min 10s ago
 Invocation: 795098e4e5484746a214472bb672a74b
    Process: 822 ExecStartPre=/bin/sh -c /usr/bin/echo "both" > /tmp/gpionames/LEAK_BMC_L/edge (code=exited, status=0/SUCCESS)
   Main PID: 825 (leakage-mond)
        CPU: 5.114s
     CGroup: /system.slice/leakage-mond.service
             └─825 /usr/local/bin/leakage-mond -e -i -o -I /tmp/gpionames/LEAK_BMC_L/value -O /tmp/gpionames/LEAK_DISABLE_PWR_L/value

Dec 19 15:48:02 bmc-oob. systemd[1]: Starting Run leakage-mond in OpenBMC...
Dec 19 15:48:02 bmc-oob. systemd[1]: Started Run leakage-mond in OpenBMC.
Dec 19 15:48:02 bmc-oob. leakage-mond[825]: Starting Leakage-monitor
Dec 19 15:48:02 bmc-oob. leakage-mond[825]: Initial leakage state: normal
Dec 19 15:48:02 bmc-oob. leakage-mond[825]: Polling for event
Dec 19 15:49:08 bmc-oob. leakage-mond[825]: Leakage state changed to alert
root@bmc-oob:~# cat /tmp/gpionames/LEAK_BMC_L/value
0
root@bmc-oob:~# cat /tmp/gpionames/LEAK_DISABLE_PWR_L/value
0
root@bmc-oob:~# i2cget -f -y 12 0x60 0x15
Error: Read failed
root@bmc-oob:~#
```

then the MCBCPLD won't to be accesses from BMC, needs manually re-plug power cord of unit to recovery it.

From HW probe, the BMC response in 380us
![image](https://github.com/user-attachments/assets/f71532d3-d781-4d09-bacd-b20a16accfeb)

Reviewed By: mikechoifb

Differential Revision: D73908495

Pulled By: ezeob002

fbshipit-source-id: 7add51c5349444f0de40f2f991dfe24cbd26efce