icecube800bc: recipes-utils: Update board-utils and setup-gpio
Summary:
# Description

Update board-utils and setup-gpio scripts to add required functionalities.

# Motivation

To add required functionalities to Icecube800bc platform:

1. wedge_board_rev : To check platform variant
2. wedge_power.sh on : To power on COMe
3. wedge_power.sh off : To power off COMe
4. wedge_power.sh reset : To warm reset COMe
5. wedge_power.sh status : To check COMe power status

Export GPIO:

1. BMC_I2C2_EN

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1854

Test Plan:
1. Run all supported commands:
```
root@bmc-oob:~# source /usr/local/bin/openbmc-utils.sh
root@bmc-oob:~# wedge_board_type
icecube800bc
root@bmc-oob:~# wedge_board_rev
Board type: unknown value []
Revision: Pre-EVT & EVT1
root@bmc-oob:~# wedge_power.sh status
Microserver power is on
root@bmc-oob:~# wedge_power.sh off
Power off x86 (userver) ... Done
root@bmc-oob:~# wedge_power.sh status
Microserver power is off
root@bmc-oob:~# sol.sh

------------------TERMINAL MULTIPLEXER---------------------
  CTRL-l ?   : Display help message.
  CTRL-l x : Terminate the connection.
  /var/log/mTerm_wedge.log : Log location
  CTRL-l + b : Send Break

-----------------------------------------------------------
Connection closed.
root@bmc-oob:~#
root@bmc-oob:~# wedge_power.sh on
Power on x86 (userver) ... Done
root@bmc-oob:~# wedge_power.sh status
Microserver power is on
root@bmc-oob:~# sol.sh

------------------TERMINAL MULTIPLEXER---------------------
  CTRL-l ?   : Display help message.
  CTRL-l x : Terminate the connection.
  /var/log/mTerm_wedge.log : Log location
  CTRL-l + b : Send Break

-----------------------------------------------------------
[15][19][11][32][A1][A9][AA][A9][AF][CD][B0][C1][B1][C2][C3][AF][15][19][11][32][A1][A9][A9][A9][A8][AA][AE][AF][AF][CD][B0][C1][B1][C2][C3][B1][B4][B8][C5][B2][C6][C7][B3][B6][B6][B7][B7][B7][B7][B7][BE][D2][D6][B9][C7][C7][CC][B7][B8][C9][BA][CB][BB][D0][D0][D0][D0][D0][D1][D1][D1][CA][B7][D3][CC][BC][CE][C6][AF][4F][3B][33][60][61]ERROR: Class:0; Subclass:20000; Operation: 1002
ERROR: Class:0; Subclass:20000; Operation: 1000
[9A][62][68][69][6A][79][70][71][90][91][92][94][94]
```

2. GPIO:
```
root@bmc-oob:/tmp/gpionames# ls -a
.            ..           BMC_I2C2_EN  BMC_READY_N
root@bmc-oob:/tmp/gpionames# ls -l
lrwxrwxrwx    1 root     root            23 Dec 19 13:25 BMC_I2C2_EN -> /sys/class/gpio/gpio553
lrwxrwxrwx    1 root     root            23 Dec 19 13:25 BMC_READY_N -> /sys/class/gpio/gpio632
root@bmc-oob:/tmp/gpionames# head */direction
==> BMC_I2C2_EN/direction <==
out

==> BMC_READY_N/direction <==
out
```

Reviewed By: mikechoifb

Differential Revision: D73438553

Pulled By: ezeob002

fbshipit-source-id: 411849c5ea0162848b69f259921614a1928290c2