cit: wedge400: force read the sensor for test_sensor_scm
Summary:
# Description
override get_json_threshold_result() for adding "--force" option in test_sensor_scm

# Motivation
To fix the intermittent issue when running full CIT, caused from
- "test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_switch_reset" will reset COMe
- While BIOS booting the SOC_DIMMA and SOC_DIMMB will be NA if sensor-mon exactly interval read, NA will be cached
- next "test_sensor.ScmSensorTest.test_scm_temp_sensor_range" will be failed

![image](https://github.com/user-attachments/assets/867f7cb0-210f-41a4-8644-2e519e5a0a5e)

```
root@bmc-oob:/run/tests2# (sleep 20; sv restart sensord) &
[1] 27818
root@bmc-oob:/run/tests2# python cit_runner.py -p wedge400 -r tests.wedge400.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_switch_reset; date; python cit_runner.py -p wedge400 -r tests.wedge400.test_sensor.ScmSensorTest;
test_endpoint_api_sys_switch_reset (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok: run: sensord: (pid 28208) 0s
ok

----------------------------------------------------------------------
Ran 1 test in 91.248s

OK
[1]+  Done                    ( sleep 20; sv restart sensord )
Thu Jan 23 00:24:01 PST 2025
test_scm_sensor_keys (tests.wedge400.test_sensor.ScmSensorTest) ... ok
test_scm_temp_sensor_range (tests.wedge400.test_sensor.ScmSensorTest) ...
======================================================================
FAIL: test_scm_temp_sensor_range (tests.wedge400.test_sensor.ScmSensorTest) (key='SOC_DIMMA_TEMP')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/run/tests2/tests/wedge400/test_sensor.py", line 84, in test_scm_temp_sensor_range
    self.assertNotEqual(  # Assert if value is N/A
AssertionError: 'NA' == 'NA' : Sensor=SOC_DIMMA_TEMP, reported value=NA, is unmeasurable

======================================================================
FAIL: test_scm_temp_sensor_range (tests.wedge400.test_sensor.ScmSensorTest) (key='SOC_DIMMB_TEMP')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/run/tests2/tests/wedge400/test_sensor.py", line 84, in test_scm_temp_sensor_range
    self.assertNotEqual(  # Assert if value is N/A
AssertionError: 'NA' == 'NA' : Sensor=SOC_DIMMB_TEMP, reported value=NA, is unmeasurable

----------------------------------------------------------------------
Ran 2 tests in 3.464s

FAILED (failures=2)
root@bmc-oob:/run/tests2#
```

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1828

Test Plan:
validate in Wedge400C DVT with specific CIT test cases,
```
root@bmc-oob:/run/tests2# (sleep 20; sv restart sensord) &
[1] 30048
root@bmc-oob:/run/tests2# python cit_runner.py -p wedge400 -r tests.wedge400.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_switch_reset; date; python cit_runner.py -p wedge400 -r tests.wedge400.test_sensor.ScmSensorTest;
test_endpoint_api_sys_switch_reset (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok: run: sensord: (pid 30437) 0s
ok

----------------------------------------------------------------------
Ran 1 test in 183.013s

OK
[1]+  Done                    ( sleep 20; sv restart sensord )
Thu Jan 23 19:42:36 PST 2025
test_scm_sensor_keys (tests.wedge400.test_sensor.ScmSensorTest) ... ok
test_scm_temp_sensor_range (tests.wedge400.test_sensor.ScmSensorTest) ... ok

----------------------------------------------------------------------
Ran 2 tests in 19.797s

OK
root@bmc-oob:/run/tests2#
...

Reviewed By: tao-ren

Differential Revision: D69229232

fbshipit-source-id: 745b7507a4012257519e604c8629363212870f32