Handle invalid severity in HMC events gracefully
Summary:
There's some speculation that the HMC might return `"Fatal"` for the
severity on some events. I haven't confirmed this myself, but it seems
reasonable to expect, because I've already seen `"Informational"`,
which is also out-of-spec behavior. With that in mind, I've added a new
unit test for this case and refactored the severity handling to avoid
assuming that it decodes to any enum variant successfully. Just default
to `"Critical"` and include a log message if the severity is wrong.

This change can be landed and deployed without blocking the current
release: the only caveat is that some HMC events may be dropped (not
included in the BMC event logs) if they include an invalid severity
value like "Fatal".

Test Plan:
Before:

```
$ cargo test -- --nocapture test_hmc
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.10s
     Running unittests src/lib.rs (target/debug/deps/satellite_relay-8bde2144a36b444d)

running 1 test
thread 'redfish::tests::test_hmc_schema_violations' panicked at src/redfish.rs:251:68:
called `Result::unwrap()` on an `Err` value: Error("unknown variant `Fatal`, expected one of `Invalid`, `OK`, `Warning`, `Critical`, `Informational`", line: 0, column: 0)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test redfish::tests::test_hmc_schema_violations ... FAILED

failures:

failures:
    redfish::tests::test_hmc_schema_violations

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 3 filtered out; finished in 0.00s
```

After:

```
$ cargo test
   Compiling satellite-relay v0.1.0 (/home/pdel/meta-openbmc/meta-facebook/meta-catalina/recipes-catalina/satellite-relay/files)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 2.48s
     Running unittests src/lib.rs (target/debug/deps/satellite_relay-8bde2144a36b444d)

running 4 tests
test dbus::tests::test_enum_repr ... ok
test dbus::tests::test_invalid_severity ... ok
test dbus::tests::test_storage_warning_to_sel ... ok
test dbus::tests::test_cper_to_sel ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/main.rs (target/debug/deps/satellite_relay-86fd99aff238b9ae)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests satellite_relay

running 2 tests
test src/dbus.rs - dbus::SatelliteControllerConfigurationProxy (line 72) - compile ... ok
test src/dbus.rs - dbus::ObjectMapperProxy (line 18) - compile ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.07s

```

# On a live BMC:

```
root@rtptest248-oob:~# curl -k -X POST http://172.31.13.241:8888 -H "Content-Type: application/json" -d '{"Id": "1234", "Name": "blah", "Events": [{"Message":"Testing severity","Severity":"Fatal"}]}'
```

Before:

```
Jan 21 16:43:12 rtptest248-oob.nha6.facebook.com satellite-relay[16229]: 2025-01-22T00:43:12.635525Z ERROR satellite_relay::error: Relay error
Jan 21 16:43:12 rtptest248-oob.nha6.facebook.com satellite-relay[16229]: Caused by:
Jan 21 16:43:12 rtptest248-oob.nha6.facebook.com satellite-relay[16229]:     0: Error decoding Event: {"Id": "1234", "Name": "blah", "Events": [{"Message":"Testing severity","Severity":"Fatal"}]}
Jan 21 16:43:12 rtptest248-oob.nha6.facebook.com satellite-relay[16229]:     1: unknown variant `Fatal`, expected one of `Invalid`, `OK`, `Warning`, `Critical`, `Informational` at line 1 column 90
```

After:

```
2025-01-22T01:09:27.658767Z  INFO satellite_relay: {"Id": "1234", "Name": "blah", "Events": [{"Message":"Testing severity","Severity":"Fatal"}]}
2025-01-22T01:09:27.660172Z ERROR satellite_relay::dbus: Invalid severity: Some(String("Fatal"))

Caused by:
    unknown variant `Fatal`, expected one of `OK`, `Warning`, `Critical`
2025-01-22T01:09:27.694889Z  INFO satellite_relay: Created log entry /xyz/openbmc_project/logging/entry/2262
$ mfg-tool log-display
...

    "2262": {
        "additional_data": {
            "Message": "Testing severity",
            "MessageId": "",
            "MessageSeverity": "Fatal"
        },
        "event_id": "",
        "message": "Testing severity",
        "resolution": "",
        "resolved": false,
        "severity": "xyz.openbmc_project.Logging.Entry.Level.Warning",
        "timestamp": "2025-01-22T00:41:47.535000000Z",
        "updated_timestamp": "2025-01-22T00:41:47.535000000Z"
    },
```

Reviewed By: williamspatrick

Differential Revision: D68465242

fbshipit-source-id: 9e087affc5f11802c27f65d2b0ddf5e57aec88fb