netlakemtp: Add Infineon TDA38640A Rev5 driver function for VR firmware update
Summary:
Description:
 1. Check TDA38640 chip revision at runtime and invoke the appropriate update routine (e.g., TDA38640 rev4 or TDA38640A rev5).
 2. For Netlake MB MP testing and the version is netlakemtp-v2025.16.a1

Motivation:
 Ensure compatibility with newer hardware revisions and apply correct firmware logic for each version.

X-link: https://github.com/facebookexternal/openbmc.wiwynn/pull/3312

Test Plan:
1.Build code: Pass
 2.Confirm Rev5 devices follow new update routine

Log:
 root@bmc-oob:/tmp/tda38640_test# fw-util all --version
 BMC Version: netlakemtp-v2025.16.a1
 BMC Version After Activated: netlakemtp-v2025.16.a1
 Fan Speed Controller Version: NA
 ROM Version: netlakemtp-v2025.16.a1
 ROM Version After Activated: netlakemtp-v2025.16.a1
 TPM Version: 7.85
 Broadcom NIC Version: 220.0.87.0
 BIOS Version: NL403
 SERVER CPLD Version: 00010401
 ME Version: SPS_05.00.04.100.0
 VR_1V05_STBY Version: Infineon dc9ef246, Remaining Write: 7
 VR_VCCIN/VR_1V8_STBY Version: Infineon 66e33f72, Remaining Write: 19
 VR_VCCANA_CPU Version: Infineon 4b411349, Remaining Write: 0
 VR_VDDQ Version: Infineon 7e5e4775, Remaining Write: 2
 VR_VNN_PCH Version: Infineon 43374369, Remaining Write: 4

 root@bmc-oob:/tmp/tda38640_test# fw-util server --update vr_1v05_stby TDA38640A_Wiwynn_22_P1V05_CL_20230615-0xDC9EF246.mic
 VR IC: INF TDA38640A rev5
 Update VR: VR_1V05_STBY
 the checksum is the same as the current firmware!
 Please use "--force" option to try again.
 ERROR: VR Firmware update failed!
 Upgrade of server : vr_1v05_stby failed

 root@bmc-oob:/tmp/tda38640_test# fw-util server --update vr_1v05_stby TDA38640A_Wiwynn_22_P1V05_CL_20250406.mic
 VR IC: INF TDA38640A rev5
 Update VR: VR_1V05_STBY
 Remaining Writes: 7
 Upgrade of server : vr_1v05_stby succeeded

 root@bmc-oob:/tmp/tda38640_test# fw-util server --update vr_1v05_stby TDA38640A_Wiwynn_22_P1V05_CL_20250406.mic
 VR IC: INF TDA38640A rev5
 Update VR: VR_1V05_STBY
 the checksum is the same as the current firmware!
 Please use "--force" option to try again.
 ERROR: VR Firmware update failed!
 Upgrade of server : vr_1v05_stby failed

 root@bmc-oob:/tmp/tda38640_test# fw-util all --version
 BMC Version: netlakemtp-v2025.16.a1
 BMC Version After Activated: netlakemtp-v2025.16.a1
 Fan Speed Controller Version: NA
 ROM Version: netlakemtp-v2025.16.a1
 ROM Version After Activated: netlakemtp-v2025.16.a1
 TPM Version: 7.85
 Broadcom NIC Version: 220.0.87.0
 BIOS Version: NL403
 SERVER CPLD Version: 00010401
 ME Version: SPS_05.00.04.100.0
 VR_1V05_STBY Version: Infineon dc9ef246, Remaining Write: 7
 VR_VCCIN/VR_1V8_STBY Version: Infineon 66e33f72, Remaining Write: 19
 VR_VCCANA_CPU Version: Infineon 4b411349, Remaining Write: 0
 VR_VDDQ Version: Infineon 7e5e4775, Remaining Write: 2
 VR_VNN_PCH Version: Infineon 43374369, Remaining Write: 4

 root@bmc-oob:/tmp/tda38640_test# fw-util server --force --update vr_1v05_stby TDA38640A_Wiwynn_22_P1V05_CL_20250406.mic
 VR IC: INF TDA38640A rev5
 Update VR: VR_1V05_STBY
 Remaining Writes: 6
 Force upgrade of server : vr_1v05_stby succeeded

 root@bmc-oob:/tmp/tda38640_test# fw-util all --version
 BMC Version: netlakemtp-v2025.16.a1
 BMC Version After Activated: netlakemtp-v2025.16.a1
 Fan Speed Controller Version: NA
 ROM Version: netlakemtp-v2025.16.a1
 ROM Version After Activated: netlakemtp-v2025.16.a1
 TPM Version: 7.85
 Broadcom NIC Version: 220.0.87.0
 BIOS Version: NL403
 SERVER CPLD Version: 00010401
 ME Version: SPS_05.00.04.100.0
 VR_1V05_STBY Version: Infineon dc9ef246, Remaining Write: 7
 VR_VCCIN/VR_1V8_STBY Version: Infineon 66e33f72, Remaining Write: 19
 VR_VCCANA_CPU Version: Infineon 4b411349, Remaining Write: 0
 VR_VDDQ Version: Infineon 7e5e4775, Remaining Write: 2
 VR_VNN_PCH Version: Infineon 43374369, Remaining Write: 4

 root@bmc-oob:/tmp/tda38640_test# power-util sled-cycle

 root@bmc-oob:~# fw-util all --version
 BMC Version: netlakemtp-v2025.16.a1
 BMC Version After Activated: netlakemtp-v2025.16.a1
 Fan Speed Controller Version: NA
 ROM Version: netlakemtp-v2025.16.a1
 ROM Version After Activated: netlakemtp-v2025.16.a1
 TPM Version: 7.85
 Broadcom NIC Version: 220.0.87.0
 BIOS Version: NL403
 SERVER CPLD Version: 00010401
 ME Version: SPS_05.00.04.100.0
 VR_1V05_STBY Version: Infineon 44f4e11d, Remaining Write: 5
 VR_VCCIN/VR_1V8_STBY Version: Infineon 66e33f72, Remaining Write: 19
 VR_VCCANA_CPU Version: Infineon 4b411349, Remaining Write: 0
 VR_VDDQ Version: Infineon 7e5e4775, Remaining Write: 2
 VR_VNN_PCH Version: Infineon 43374369, Remaining Write: 4

 root@bmc-oob:~# log-util all --print | grep fw-util
 0    all      2025-04-14 22:04:24    fw-util          BMC fw upgrade initiated
 0    all      2025-04-14 22:06:05    fw-util          BMC fw upgrade completed. Version: netlakemtp-v2025.16.a1
 0    all      2025-04-14 22:06:06    fw-util          BMC fw upgrade initiated
 0    all      2025-04-14 22:07:46    fw-util          BMC fw upgrade completed. Version: netlakemtp-v2025.16.a1
 0    all      2025-04-14 22:11:52    fw-util          Component vr_1v05_stby upgrade initiated
 0    all      2025-04-14 22:12:10    fw-util          Component vr_1v05_stby upgrade initiated
 0    all      2025-04-14 22:12:11    fw-util          Component vr_1v05_stby upgrade completed
 0    all      2025-04-14 22:12:19    fw-util          Component vr_1v05_stby upgrade initiated
 0    all      2025-04-14 22:12:44    fw-util          Component vr_1v05_stby upgrade initiated
 0    all      2025-04-14 22:12:45    fw-util          Component vr_1v05_stby force upgrade completed

# Description

Please include a summary of the change and which issue is fixed.

# Motivation

Please include an explanation of why you these changes are necessary

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Reviewed By: jamesatha

Differential Revision: D74445262

fbshipit-source-id: 0939a07ac60253dce07f5543a9cf57be145a9cc9