tools: fboss-lite: fix gen_eeprom to meet expected weutil config file
Summary:
# Description
tools: fboss-lite: fix gen_eeprom to meet expected weutil configuration file

# Motivation
Fix the issue, weutil cannot parse the eeprom device from eepron.conf was generated by fboss-lite-new.py

because the key is different from fboss-lite weutil source code
```
root@bmc-oob:~# cat /etc/weutil/eeprom.json
{
    "platform_name": "icecube800bc",
    "eeproms": [
        {
            "name": "chassis_eeprom",
            "address": "/sys/bus/i2c/devices/6-0053/eeprom"
        }
    ]
}
root@bmc-oob:~# weutil
ERROR: invalid eeprom device name: chassis_eeprom
root@bmc-oob:~#
```

```diff
{
    "platform_name": "new",
-   "eeproms": [
+   "eeprom devices": [
        {
            "name": "chassis_eeprom",
-           "address": "/sys/bus/i2c/devices/6-0053/eeprom"
+           "sysfs_path": "/sys/bus/i2c/devices/6-0053/eeprom"
        }
    ]
}
```

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1829

Test Plan:
1. generate new platform by new-fblite.py  with json config file

```json
{
  "eeprom devices" : [
    {
      "name" : "chassis_eeprom",
      "sysfs_path" : "/sys/bus/i2c/devices/6-0053/eeprom"
    }
  ],
  "...":"..."
}
```
```
$ python3 tools/fboss-lite/new-fblite.py -n new -p all -d /conf/new.json
```
2. build the image, validate on Minipack3 platform
3. manual add eeprom driver, and use weutil to display infomation.
```
root@bmc-oob:~# echo 24c64 0x53 > /sys/bus/i2c/devices/i2c-6/new_device
[ 1987.933215] i2c i2c-6: newvice: Instanted device 24cat 0x53
root@bmc-oob:~# [ 1988.020905] at24 6-0053:  byte 24c64 EOM, writable,bytes/write

root@bmc-oob:~# weutil
Version: 5
Product Name: MINIPACK3
Product Part Number: 30100032
System Assembly Part Number: 0
Meta PCBA Part Number: 132100032
Meta PCB Part Number: 131100011
ODM/JDM PCBA Part Number: R3214G001202
ODM/JDM PCBA Serial Number: A122224210004
Product Production State: 2
Product Version: 1
Product Sub-Version: 0
Product Serial Number: F502224220067
System Manufacturer: CLS
System Manufacturing Date: 20240607
PCB Manufacturer: GCE
Assembled At: CTH
EEPROM location on Fabric: FCB
BMC MAC Base: b4:db:91:95:4e:26
BMC MAC Address Size: 1
Switch ASIC MAC Base: b4:db:91:95:4e:28
Switch ASIC MAC Address Size: 1
CRC16: 0x3468 (CRC Mismatch. Expected 0x9dfd)
root@bmc-oob:~#
```

Reviewed By: mikechoifb

Differential Revision: D69667290

fbshipit-source-id: 3a3a9333df220ce1ba52ae5fa0443204137567ac