netlakemtp:Support Meta FBOSS EEPROM Format v6 and Optimize weutil
Summary:
# Description
 1.Update weutil to support decode Meta FBOSS EEPROM Format v6 from meta-foss-lite.
   link:https://github.com/facebookexternal/openbmc.wiwynn/tree/main/meta-facebook/meta-fboss-lite/recipes-utils/wedge-eeprom
 2.Base on wedge-eeprom code base add write/dump/modify eepromfunction,let weutil support more function.
 3.Let weutil can support both FBOSS v5 and v6 format by using decode/modify eeprom.
 4.Optimize the output log format.
 5.Revise CRC calculation data string.
 6.Avoid enter the null vale in ASII data string.
 7.Avoid get ERROR CRC TLV data byte.

# Motivation
 1.Let Netlake BMC support Meta FBOSS V5/V6 EEPROM format.
 2.To prevent incorrect writing cause the eeprom format not match Meta FBOSS V5/V6.

X-link: https://github.com/facebookexternal/openbmc.wiwynn/pull/3279

Test Plan:
1.Build code: Pass.
 2.Test weutil action is correct.

# Log
 1.Display weutil function:
 root@bmc-oob:~# weutil -h
 weutil [-h | --help] [-a | --all] [-j | --json] [-f | --format] [-l |--list] [-e <dev-name> | --eeprom <dev-name>]
        [-w <file> | --write <file>] [-m <Type> <Value> | --modify <Type> <Value>] [-d <file> | --dump <file>] [-v | --version]
   -h | --help : show usage.
   -a | --all : print all eeprom devices data.
   -j | --json : print eeprom data in JSON format.
   -e | --eeprom : eeprom device name.
   -f | --format : eeprom format.
   -l | --list : list all eeprom device names.
   -w | --write : write file data to eeprom.
   -m | --modify : modify type value to eeprom,rules are at the bottom.
        [Type]  |                     [Name]                   |  [Length]
       -------------------------------------------------------------------------
          1     |  Product Name                                |   Variable
          2     |  Product Part Number                         |   Variable
          3     |  System Assembly Part Number                 |      8
          4     |  Meta PCBA Part Number                       |      12
          5     |  Meta PCB Part Number                        |      12
          6     |  ODM/JDM PCBA Part Number                    |   Variable
          7     |  ODM/JDM PCBA Serial Number                  |   Variable
          8     |  Product Production State                    |      1
          9     |  Product Version                             |      1
          10    |  Product Sub-Version                         |      1
          11    |  Product Serial Number                       |   Variable
          12    |  System Manufacturer                         |   Variable
          13    |  System Manufacturing Date                   |      8
          14    |  PCB Manufacturer                            |   Variable
          15    |  Assembled at                                |   Variable
          16    |  EEPROM location on Fabric                   |   Variable
          17    |  X86 CPU (MAC Base + MAC Address Size)       |      8
          18    |  BMC (MAC Base + BMC MAC Address Size)       |      8
          19    |  Switch ASIC (MAC Base + MAC Address Size)   |      8
          20    |  META Reserved (MAC Base + MAC Address Size) |      8
          21    |  RMA (only for FBOSS v6 format)              |      1
       -------------------------------------------------------------------------
          Notice: Type 17~20 need to add - before enter MAC Address Size.
          ex. weutil -m 17 11:22:33:44:55:66-258
   -d | --dump : dump eeprom as a file.
        ex. weutil -d aaa.bin or weutil -d /home/aaa.bin
   -v | --version : show the weutil version.

 2.Check weutil can decode and check FBOSS v5 and v6 format
 (check FBOSS V6 format)
 root@bmc-oob:~# weutil
 Version: 6
 Product Name: FIRST_SQUEEZE
 Product Part Number: 20123456
 System Assembly Part Number: SYSA1234
 Meta PCBA Part Number: PCBA1234567
 Meta PCB Part Number: PCB12345678
 ODM/JDM PCBA Part Number: MYODM1234567
 ODM/JDM PCBA Serial Number: OS123456789AB
 Product Production State: 1
 Product Version: 0
 Product Sub-Version: 1
 Product Serial Number: PS1234567890A
 System Manufacturer: UNA_MAS
 System Manufacturing Date: 20130203
 PCB Manufacturer: TERZO
 Assembled At: JUICETORY
 EEPROM location on Fabric: BUDOKAN
 X86 CPU MAC Base: 11:22:33:44:55:66
 X86 CPU MAC Address Size: 258
 BMC MAC Base: 12:34:56:78:9a:bc
 BMC MAC Address Size: 772
 Switch ASIC MAC Base: 66:55:44:33:22:11
 Switch ASIC MAC Address Size: 512
 META Reserved MAC Base: fe:dc:ba:98:76:54
 META Reserved MAC Address Size: 2
 RMA: 1
 Vendor Defined Field 1: 0x0101010101
 Vendor Defined Field 2: 0x48656c6c6f
 Vendor Defined Field 3:
 CRC16: 0x4a05 (CRC Matched)

 (get incorrect CRC value)
 root@bmc-oob:~# weutil
 Version: 6
 Product Name: NETLAKE
 Product Part Number: NA
 System Assembly Part Number: NA
 Meta PCBA Part Number: NA
 Meta PCB Part Number: NA
 ODM/JDM PCBA Part Number: NA
 ODM/JDM PCBA Serial Number: NA
 Product Production State: 4
 Product Version: 0
 Product Sub-Version: 0
 Product Serial Number: NA
 System Manufacturer: WIWYNN
 System Manufacturing Date: NA
 PCB Manufacturer: NA
 Assembled At: WYTN
 EEPROM location on Fabric: U20
 X86 CPU MAC Base: 00:00:00:00:00:00
 X86 CPU MAC Address Size: 0
 BMC MAC Base: 00:00:00:00:00:00
 BMC MAC Address Size: 0
 Switch ASIC MAC Base: 00:00:00:00:00:00
 Switch ASIC MAC Address Size: 0
 META Reserved MAC Base: 00:00:00:00:00:00
 META Reserved MAC Address Size: 0
 RMA: 0
 Vendor Defined Field 1:
 Vendor Defined Field 2:
 Vendor Defined Field 3:
 CRC16: 0x1234 (CRC Mismatch. Expected 0xbcfa)

 (check FBOSS V5 format)
 root@bmc-oob:~# weutil
 Version: 5
 Product Name: NETLAKE
 Product Part Number: NA
 System Assembly Part Number: NA
 Meta PCBA Part Number: NA
 Meta PCB Part Number: NA
 ODM/JDM PCBA Part Number: NA
 ODM/JDM PCBA Serial Number: NA
 Product Production State: 4
 Product Version: 0
 Product Sub-Version: 0
 Product Serial Number: NA
 System Manufacturer: WIWYNN
 System Manufacturing Date: NA
 PCB Manufacturer: NA
 Assembled At: WYTN
 EEPROM location on Fabric: U20
 X86 CPU MAC Base: 00:00:00:00:00:00
 X86 CPU MAC Address Size: 0
 BMC MAC Base: 00:00:00:00:00:00
 BMC MAC Address Size: 0
 Switch ASIC MAC Base: 00:00:00:00:00:00
 Switch ASIC MAC Address Size: 0
 META Reserved MAC Base: 00:00:00:00:00:00
 META Reserved MAC Address Size: 0
 CRC16: 0xbdba (CRC Matched)

 3.check weutil modify function
 (example)
 root@bmc-oob:~# weutil -m 1 Meta
 Read netlake-eeprom ------- [Pass]
 Check Header -------------- [Pass]
 Check CRC TLV ------------- [Pass]
 Modify Value -------------- [Pass]
 Calculate CRC-CCITT_AUG --- [Pass]
 --------------------------------------------
 [EEPROM Data Format : Meta FBOSS V6]
 [Write new Data to netlake-eeprom Success!]
 root@bmc-oob:~#
 root@bmc-oob:~# weutil
 Version: 6
 Product Name: Meta
 Product Part Number: 20123456
 System Assembly Part Number: SYSA1234
 Meta PCBA Part Number: PCBA1234567
 Meta PCB Part Number: PCB12345678
 ODM/JDM PCBA Part Number: MYODM1234567
 ODM/JDM PCBA Serial Number: OS123456789AB
 Product Production State: 1
 Product Version: 0
 Product Sub-Version: 1
 Product Serial Number: PS1234567890A
 System Manufacturer: UNA_MAS
 System Manufacturing Date: 20130203
 PCB Manufacturer: TERZO
 Assembled At: JUICETORY
 EEPROM location on Fabric: BUDOKAN
 X86 CPU MAC Base: 11:22:33:44:55:66
 X86 CPU MAC Address Size: 258
 BMC MAC Base: 12:34:56:78:9a:bc
 BMC MAC Address Size: 772
 Switch ASIC MAC Base: 66:55:44:33:22:11
 Switch ASIC MAC Address Size: 512
 META Reserved MAC Base: fe:dc:ba:98:76:54
 META Reserved MAC Address Size: 2
 RMA: 1
 Vendor Defined Field 1: 0x0101010101
 Vendor Defined Field 2: 0x48656c6c6f
 Vendor Defined Field 3:
 CRC16: 0x72bb (CRC Matched)

 (error case sample)
 root@bmc-oob:~# weutil -m 1 ""

 ERROR: Type 1 can't not bo NULL data !

 root@bmc-oob:~# weutil -m 22 Wiwynn

 ERROR: Type is modify incorrect !
 Meta FBOSS v5 Type is between 1~20 !
 Meta FBOSS v6 Type is between 1~21 !

 root@bmc-oob:~# weutil -m 21 1
 Read netlake-eeprom ------- [Pass]
 Check Header -------------- [Pass]

 ERROR: Type 21 is not in FBOSS V5 format !

Reviewed By: jamesatha

Differential Revision: D71191696

fbshipit-source-id: f1ddc5333b681c37de5d7bd5d4a7604e21f66242